---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az"
