ansible_become_pass: ENC[AES256_GCM,data:/zLqqSZfieCeXVtPsxupVpW5ew==,iv:yTyC55TnqDhSEVjvK0Bq9A9+2cxqpcBrM7qQVDMOdto=,tag:g9ce+FPxhGZEHMAivMMH1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZnBEbTFXQWlZSzlUWDJv
            cnFhdmRudWNPZWZHeDFCcDNwZWRFNEpwR3kwCnR3bDdXRkFYOVJwTXllNThkQTJZ
            TTZjVGVEdVFkb2hKZURGR1N2b2NCOTQKLS0tIGZwNlRxdUNZcnhwcTQ4NkV0NkxO
            MmNmYWVTZG5hZmRNQzdVWFhqSm1ub2cKMsOTxGVkohD+acRk/C+ocdOvWaj1Im16
            Ddxu3NNA6I+kk2rYEh7O5+VWrCGDJXTVxfDdzSuOXbkCUKzOpRgy8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T01:25:42Z"
    mac: ENC[AES256_GCM,data:DCz1MBmlZl+q0nW1x4G/yv52GGlVp6z9xwbxcgnZI2Vr7z3u9bfa1tahW6NwLlKnzhd+taJlYp35v9iY800S44hPb9owbYbLwodtocysrdLSShaizQ69A3MVl+ffZ+/OGtnO6scXcIeHy+oABVqLhjWj+MzkTU0G/cVIoP09msE=,iv:b8h/4EihFN9b+OBtj5QDQ7NPUdmcaCEfFoX8k1i5gfM=,tag:wdLuRUnuCWkmQP9nla7PSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
