ansible_become_pass: ENC[AES256_GCM,data:he3iNpI6LiIxncIGYjHQu+jArQ==,iv:OlJ7yQyfrGCf+OGoDs/F2m1rXmOql3WWIKs0Mqs0qsk=,tag:caCB/tE2uMPVY3N/aj7D3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIakhQSWxsQlBtT1ZLSC9C
            OUQ3QlFLUlpoS2Vrd2JZYWtlbkQyb1JqbXhJCkhHcTZFNktVWFYzaDMyYisxWDlE
            dFRUSU56OTkwcUFuWUg3eXZ5TUd6YzQKLS0tIDNtb1pnM3JoeHFSdlpVZ2QrTnNt
            Mk4zN0lzNW1JK0NtaTZZc0JzeWllN0UKw0pHOnBVqdQUKzj4F5plH3J5W7+93SBY
            sWxakvukccaCzkQ36lqOgSRgAKSZddtonbqiEaD2ovl4Y9rEJomf8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T21:54:04Z"
    mac: ENC[AES256_GCM,data:wIHfQpuNrp5Dt0pveIFuigro4ImXKtUuS8J+T153KI+UmaW8YIGVnfjcN9i3cltpfKJ1aHhBTdrsVJDgTN7NupAlb79mZAfEAhjcjCAbQciLJ4KpqmMosmL01VYIG5fIRurgRj3Ys5EB41FFsKNRezxJFQ0ZgTOZp29ywSGYYXA=,iv:/Bo/LGz4S/6iO1Qbz8iflxQcg9Ur88q3OVNn4hGh3ZE=,tag:TseYsjyuVvsiJtjKuIm/SA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
