ansible_become_pass: ENC[AES256_GCM,data:nvP9HeGvs/VrffRTJqGCX3nIuQ==,iv:MJTatRYJ4LyxwJmATzjqcz+qQHbimUS0mbhmq7YzqbQ=,tag:5usvVYqgZIN58dOmvwN9xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cy9GWGtZdExnd0RxQlhB
            K2tyQ25DNWFIVm44eFcwVFdhWkhhSisrSDBNCklqM0ZJUnRweEdWMm1RZVE3bzE2
            UEhud3Ftc2FFZXhzU1ViY0FXNmpaMGcKLS0tIFFkQ0R0U1MrYVBPUEJ6UkFRVVgr
            SmNRM09ucTZMUGtQZUdmYlF1ZFkwYTgKpQQa98dUXmTzgnUW8rmeEGb26EF9F+pk
            9SrElZGoeL2l4F+33lG25zlicrzR2gdFXrzVe9iR+RfHvp6KeYsq7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T00:53:12Z"
    mac: ENC[AES256_GCM,data:KLJGN2gjPxdCT5nezkeshPYJVJQ0XzPJGxlyBmaqQh2ajGIaYKgcDqML8LLSZK4aisia7zTioJaYkV4g7Z9xjUCXAalDwMeDDlMv5CdrbYkPLnsxm1LnEHWyaADrC7WMB/wvV3S1U97CXi1o9jbDUt0vm0HbHoEhamIpgiZLT8U=,iv:ALF/nieJElQwJfMX27+v+arx9YjW+6NY3K2sA+coKUY=,tag:nOdSaSJCBb17XH98/MBaig==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
