ansible_become_pass: ENC[AES256_GCM,data:6MqzuXem8gSADJxh/6Y3BOy6SA==,iv:6EY2y6bNQxZOMq8oqLYnUQc5TNJt7EB8iKfy4qXgqqk=,tag:d+1EMorpe+pYeFIRaHuUXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSVU0TzRZaDdTSnRrUXZW
            Tjd6dWVYUldsZEFzWUN5dDJJTTRacmFqeXhvCnpYWmVsdCtQOUp2WGFxZ25HSHEx
            QXJwRW5Rb1c2T0FqMUdweVF6R0RDaWsKLS0tIFY2ZE5FSzFaZzhKOERLN3hYWlJ2
            bHJ0Mkk0Z0s5UFZPZXRFY1hEbU9DS2cK4J/XCYOY3j9w7OMbuQENipnlbiIbwpVP
            LwehhfL6eGQo4fxqU08sAbWdWyPzJRaPKHcDkyMd8lGcYYXDWTO4mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:25:29Z"
    mac: ENC[AES256_GCM,data:ZefsvQBUVSesAiJYNJ78G65OAf+lYqhT/m7rOHfcW2OxHLk6L01IvD8pJbrc4j/EHA6P9PPufevI2LRDpf4VFXxoDjyoNrtd9DPh7UBJNhDdMNkBl4cic63qvda/kyv0D6XuVdcCF83ESLlZkYwOl+Wa+gLomLJ0KhvH9a8vaAU=,iv:tN+ITNp7ivL+EHn0UC1C45KTC8wsnJequiglM2kKWKg=,tag:FyTo1e6JTEhoOuGsh4AXPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
