ansible_become_pass: ENC[AES256_GCM,data:Oh4mdHVYEPs/yNc6PzXbelFrHw==,iv:5c+8vwpLz036yNal0AGztcfJkULw9cPT0pSGjJMgp+Q=,tag:nawLbBhpDXwuAue1OEKdAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRL0VDVTNxSTVqcWdlcmR2
            U09lNlRWNjNweVRqZ2tCZlB4TGY1TEVWTkF3ClZGOTJTbEZjOHdXVU1xTTcxTlhI
            aVZiRW40TW5TM1I3c01OSXZwdUlSdUkKLS0tIHVFTXNqU2JvejFPT015Rnp0dlBU
            eHAycWc2SmtsVVhQWHBiRTlla1BXMFkKeiEnkS3KL/qB2EUZxfFqbr+DwlKzqiV8
            G/7fxjEfqAKJmRJGthV6MDKckcyCaD5NbpTHXkYcmiqbMgwy9GjCmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T23:22:37Z"
    mac: ENC[AES256_GCM,data:OkXjypxTFayggb/lYpjWB5zXZ7GrmAWgC6YW1N9CUpxB7OpDFvpqHzX4R+6BTOA4kyptei/EiG5hQanA4lWdEz5RJB4d7jM2FKl3O4dQIOykWJQIjeR5Q7EphAlwxjYNLkiN3nAsGQUkeDDaejW+wak0Q7QObcGXV21Toiq+fs4=,iv:UQKKhasFnMWL+8RClA1xLLevj6+vy+Wx8iL1XknD3Os=,tag:YQe5bAyKoSd/WwxmNg5x7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
