ansible_become_pass: ENC[AES256_GCM,data:Cwa+fH+habaa9hSwzPMCFyskJQ==,iv:luzp9W3Qewm27Iu9MhSUxlhfkafUeta/k3kqfedhhH8=,tag:qC3z6Pc1GnLdU68672BkHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWkZZNjlkTjgvdkN5NXFv
            cnkydEpaMTErRmpZd3JDY1F1TkNDa01yNDJZCjZLcjhpUDZJZlFDRm9SOFcvUWZK
            dDcwaWNOOFgvRVM4K2gvVzdLWUt1L1UKLS0tIHZKWVJpVCtreDNuRUtyWVVMQ2Nn
            TElocjNvUDlWb0xKdkRGVHNwYS9RWGMKkIL4XXqcS6GARBZobYgu8KbC79VhRTcR
            I/nwaOh7wHm1V+dYYBo69aKJ1Q7rVQe8K9Nl7/fDyTrzg14BtD4pOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-05T22:16:20Z"
    mac: ENC[AES256_GCM,data:QA3epqSzdozHacsUsQ2wO+9Q45DTSEVi01HO7yJp4crZJsp71kmqWgeNeo6IikHpGMolJiYlwbTJhKRsJfIvPT5P7euwjxTefgakg9klswRBue1GXbiZvrJ69D2lmmoWg1eyCl8BMByGY9ka7l+stVZZUTONQ1UlkRlUs0FEGaU=,iv:eGJHzB0xV6iy1ROl+Dd9cnAxxDWOTiha6/PX+QNBe8c=,tag:fDCjLJ2uImWY+1RJzd1bvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
