ansible_become_pass: ENC[AES256_GCM,data:foajSBbqRsDOy1lCjv3cyNwATw==,iv:7cA28/aKF4T5KbgRHjYZkGTU2Y40y0+Nxrc9/ErwI2Y=,tag:vFRfnROTci4knyiskGkcrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbElHdTVYZnFnN3BzeGF6
            eXI2OVJIRmhOaWhtTkFRVlJmcHB6RlJMeHhnCkF0dTNhZ1czdlRNakROdHB0MVQ3
            RFZSWlIyVDJodWtrMys4b0R0ZEt2L3MKLS0tIFBTK29QTmI5cC9hcGhqWHVWK3lk
            WWFwRDhMdTFMYjEvbGxyQmFsWE04b2sK0NrfmXJN55NA0reY5VLi/gbOl9KZU2tI
            2jDRvNlTIdBmP5VHRDgV0FBP4nB2x6eXApAEC2svLXvpXHYBqj3QbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T22:07:36Z"
    mac: ENC[AES256_GCM,data:455AtdP8u/vwDHyXOteUTnaGKherYEGkrVhHeWdKsdlbfdZt65h3z6OcGIYVS50rTMkDcDMxmdaCiczm4S8jWKNqmvDdSoopfjAAVXdj/F05DNqRLkrZ+eXX0rTuqXqeIUksoqe7qQBvdpgVOnPcxjNrVpulggrluwtfcBTqSNY=,iv:LghrG3UaBvd0vf3TAxn/viLbfO3vuYutmkgcAgo6/EA=,tag:5x/fbSeprHnBp9SlTuVwSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
