apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:OvsQ0saxstM3E9lWQaITYWUMYVisSltaGRSZo4E2XcJFWXcyYpb5ig==,iv:oVytrNUiMEFG6ev/Otlzv+duCzsa8U6BgG0bPKxtf6g=,tag:V03XwwJCp2JTUrjrE0XkmA==,type:str]
    admin-user: ENC[AES256_GCM,data:HTGYPvk=,iv:ukUdDeGqovVME+scW790P+uh2L+/AtobAm2e1zT+i3I=,tag:bcEAvhCvdJ7+6VGfqbbUUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRnRKN21ENnljNlBrNlAy
            QmJMYk1XbDJTUlZNbktZMExlc1diNGltNGlFCmZ6R0RmVWN3b2I3NlFYL0ZUdk16
            WXdTbHhNc2JPRU1GR1NmVnN5ajJFdFUKLS0tIFJOakg5VDgwK2lFUVkzSCtZd2ln
            ajFBQkxKdzhJTFpoRDVrYmdwWkNxQ2sKhynOQyjv2RiQDJrjJRrj6tDE80oohgZn
            c0AXRRpkbHMYPZIbECQCNbDnNQY1TluNSkwJXCnRrJuO/7JVn70T5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T00:54:07Z"
    mac: ENC[AES256_GCM,data:kmXJkC3ThYbdyk6rgtRVwPSyWw2eBiQVm+ojAEYfYAWvBHFy9Dwqc3u6tGwlNXDkF3VDowqJ0pn9JqtTHA/UJ1bK1RgHEkxvtVZzURYndwhUEXuqTmQeSlSXBilqDZUhtMIrq/+RWvMsIyejZ+J2ycj+2xMh/8M5OwgqK2MBPQA=,iv:+HlzbhlkpdJ1F2VPFsCTzuKOEG6IJV/8sS4YcjPvXX0=,tag:NJ75bQoCbDKAoSgdx5EAeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
