apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:GLqUyi9NFybQMpgcZLLOfVBszStJIk6AdhvROwgR46g9A9oxJMqGZQ==,iv:WiU9ZSFfsJ3QgY1ErRHI9gDaYVwYSPRs+Qon3ToCUtU=,tag:dmAhNEtTF4FCEm6OkZyXwQ==,type:str]
    admin-user: ENC[AES256_GCM,data:CuMLQQA=,iv:vfyf2SvtRcyPnZke4pM74iObVY1hkdP5C/Daid0Diqg=,tag:zHgeXIf6lXecfPEKkmMcDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q2h6VklZK3JtSlhweUtT
            WG1WUGQ0Z1Q2ZlhTQ1Z4aksyc0dHMjlyVVFJCjRPSlB1WFNRdnRhY09GNFZxdjJL
            dlFlUmFEMWYzT1h3UWpNS0JIend6cWcKLS0tIEo4WW1TcW40dUFzNjhhc1FDZmJU
            dTFKcUYrRlNBcURjOWN0L3VKSmt2NWsK7YQQ8IU3HFB9NtxpbQCq+sPibpBp8X+9
            Vr7KUly+7RmnTym+RZ1ffm1x0a27EgaofmYmb12mAXeENjujsfO05w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T01:26:37Z"
    mac: ENC[AES256_GCM,data:H0rYhGal+2pkRKn6pQe/bkVjpyCDVlLYrsDv5vD7nezrVNDjuF6Fb3hsTn/cnqf3Ogwq9bI3sm0LMG20SBEH6tDbhhQQpfFX52pwWDU2FJbSHuILndEjPtCc82FKOAiSaRSh3dRN8iu1cAyMigHNWhRUtfrv7+tj1zQwb8XI6Bs=,iv:oM8Sk0IlH2ZNJvs0Ka9nnHtQTnmB6U7Z69ntKyRsm1Y=,tag:87Bjky9WxreKHp0w5HOxCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
