apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cO2ronPnzyWEQkQic2lqIhyq8r0Wpjm6,iv:yOOKOMFX8KO9/cratdw9iJfOMa7+xTRcW/w3kLilKnE=,tag:g9htrQistiLpfJM8rn2G/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbEhTYmF1RDBrNEgwRHFC
            VHRURWxCaTlaR3U4bkhzVDNWdUpYb1dOV21zCklKS0lRR01WNThIUytQVmZQZmxv
            UXR2U3grTjZNUUVOam91SmFHOGtpNzQKLS0tIGJuYnovRGQva2d1RGZHc2I4T204
            WHhqTVl4aVpvNUxpRCthbGxFYUNlcG8KsxcRcJHAHTUjM4R66wW3qtRfv0t0+vRf
            ZjjcdFhlxINuuX0PF/wQHikWaTV1EmQAj5EWVfB1yIOR5D/Ht7OPqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T02:22:37Z"
    mac: ENC[AES256_GCM,data:H01SUXk5Xq0JvB8JFTXfj2JRyVSQSku7kQpFr4nxEMnWZPNWIflXF0T6L6ue1ambuoMDHlTu09OPGr/kJVw0rLCN3Wh5BxKP0KgZvY7RehWIZgREttSy4yjrgRtr9sQVu+I0mHNWRNZuGT/+Ie9DjJxG1Uit6KY5URdnNxm8hYQ=,iv:1tM4ialk6kJY48e52hHpTd9DWDVpkVcWuapdLueFd0I=,tag:dkdqh7uUogJ4ETanE0dxKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
