apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:r20iKpkcM/CD9uBYtHRrwg+phOFOG8ss,iv:lNrLxREHEYCYc7Ex88y9n/BYA5ru0c7XQX9l0XRvoOc=,tag:8lPSOSLA5uC4Hlz68AXvpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlckxqNFdXV0FhZnpSdDZi
            Y20yMzRGYnpxTjdsc1M4bm5NWXNtTXE1M1VFCkdqMjdUWnIxZTFnWU1QM0RnMEhO
            UWp5VXdnd010N0FwU29RellYUFNleXMKLS0tIFBNK1hqZnY4Q1JQRnlBTmxCV1c4
            T2YrRnp0TGxUTGgzcHlBT1o4ZVF3bE0KjUqpcimFS+4NO3LmNlRmUNsyQU6rjuE9
            0v/+iAW1vUS9/DOi7haHzOjPzztcNiXkt3rlSt+hBfCH6fk2TZNlNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-13T01:26:27Z"
    mac: ENC[AES256_GCM,data:kRMGlfJwdreuUGlILPW3K1n2ERP0v+hXJobjeJTXf3+LLQqNJovTwIGXKlRQKFltQgG8sbAmv/Lsaan+/HEM98K0PNgp+ixQKCCAJtjywFt+HgmZ6oXyzX8s2LeTlFts7z5+QgE9Cv0CMY4gylmueq5v5pflkxg6xzdEhC3OT1M=,iv:qg8yldIOJdQNEG6/jM1WCkkcyOdl4teeF6vW/qBk0BU=,tag:o5AAm1Pm0xNVUdhDPuLXSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
