apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:4zfC7mOHwwlQzhcDz7qg+CAttFTyz00CWyeP+0/UJWqe+Yd94N/fxg==,iv:kna1Af/6gr3+zPhy3zMEcCpDyXyrY7JG60+C8qJ6Dyc=,tag:ZeYAIMQkGtYuyFTlkg2YRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbEN1QndLOEJtekQ5Nk81
            c0pmL0ovdWMxK3Z0REtFRm04Y2hQdEZXREdRCk5WY1YxT0NhWDZHVHpKY0trT2M0
            WFJhczlXaG51Y3ZEZnVuRE5FUFovYUEKLS0tIE5MaFU3M1dPMS8wd0pxQUxsWE82
            b1h6Mk1yQ1R6dk43T1BVb24yMWtMMmsKKDUY12oINSOd7zNzSStjZRARir2VzLmQ
            HayU5yM7bEUN4WuE8Ou3B7zKhIMIzrXFQME9LNnZwQ6v3a6Vje46Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:30:08Z"
    mac: ENC[AES256_GCM,data:lnh/IPETzp7a9lGgSGRCem/gpuuCDsLspo1aG8xsGhxKSpjkup+L2EYIPSIKcnWLPWKdcsm7lJfpJOsHgFTAh+f0cuk2K/Y94vKrnnGNifzM+9XwTHFai7PV0fgyC1USg/E9ixmIT69VPGOL609I3t6bwjbzd+g1U8SnBWhnquA=,iv:UdSDiFfedW3TRfYUUUvgi5H1oZCQY/siT7w0KFOP40E=,tag:6E89S6W5CbwajDclBnjo8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
