apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:A9L7FqyqKoWNqMC2UzxhYZ2WO9rDWrcx,iv:19qLg4Upht/8uHE9HcDZaqYsSIZv1G2inHw8vKj0bh4=,tag:ZmrsK1Rh4alWL4LMLuKQGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN2h5Q2dObnA0ZlAzdDhy
            REREaEFCblZ1MzJ6OGNpaUtUQi91bklVbGlRCkxTeFdWZHI2aFV2aG5sVktkYnl2
            dW1yV2tyMkF0VWNzVkh3ZHc3YTNhS3MKLS0tIEVtcDRjdGkrU29Yb1hkVlZVT3ZZ
            V2Z4QXl3SW9NekxXLzBDTHJzcEhlK2sKaeMQBSs6uiF3WA0dpW3zHcsYoN+T3crZ
            bzAeijmwejtdwNNNoxb3odNqscZEOqsjcLDKjJOlMcZjBY5+hCILKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T21:54:51Z"
    mac: ENC[AES256_GCM,data:Ci44VwvTEGq28E3aok+UzNf8flpIxGXqp9XHTM9pq288T+EY72T1TyKCDk4VxFOzKjOFA/eknHuc+wh0pH0Gu+gSQVUN4xpXjecnD21yL2LtAP6TiuABbQXfCNVjG96qGRtvBA7pVN3g8iDdgm5xG107hbLo4NknrFKCsF+Ly3c=,iv:EZ/ji79f1Fvq04WMuwUBCWo+jx0xyGtw4mxKVGQYjPM=,tag:YWsv2H/3LvyaVOh5QM+4SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
