apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:u7WKy9U9SVnb+kxWS0xuLFme0ZCfRoc0,iv:OCKLGzYp/2cAj9p8Hm2ObQdbASKmPCfC5PecZVk8G18=,tag:MzWexAAdD1XYET47MhyzbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYzNUY2hRR3pNK2VrYWRZ
            T0JFZXVGT0prMVFQa255ZHB5NnhpTU5idGpJClNjSXY0WU8wWHNPY1hFOE5pazVN
            Vll0dWd0N3FGZGQvdnBkNzdzdWxqMUUKLS0tIERwNVJFSHg1Ynk3L2RJSytJak1n
            d3dMTjFSS0tMTVFGelR5VUxUNFhzZUUKeG6I7YGYVyporWQtqcHD6bkTJdsoz8gx
            IOIR9EWQyfpa6TH5U+/uR0tLEF1+nKDpEYobSSz0yYcNTCX8fwqXFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T23:59:50Z"
    mac: ENC[AES256_GCM,data:Lu3hOVzxHD6KbD7LQ7O/Vi3CzBZ9+AqJrg2tEPUFIGED4HDppakq2GawBF/2w6f7Oson2KI8pnNFuBuxECCY2OfE4ITowAE/0FCSkovihm9EHoZTZJ2lwAdqSbJ/SQ1cJW6f7Xkzm5FQx5j+ucPWNpzlRuyihji2TEkRLC4/QaI=,iv:XTAnUU0h+uHzkWjcFwyPH2VzvGuea8YvRdRibuBNSos=,tag:E23rP0cmowv1gq71Pg5OnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
