apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:d9ABsWWryWr4YWVT4pq9vafDxD+ssCLh,iv:mHB5GQHs+eNmXrECjZcPAXi9mzNG6wl9qwU7BGOIwp4=,tag:k6zTFtD9P0dp57EofL46/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ1NBOENrTWlMWTdSRmI2
            dEhOSzJhV3VYOXZzMXMzTWtEelM1V1NWVVF3Ci81SjhqYmt6dGtlVVlMT2dWTGtL
            RUF4YzlhWFZ0Z1hhR0NnTzF1RXNUd2MKLS0tIGtrd2dtWEREaHFIM0VWTWJ0UVVX
            NEpIbHNSODUvQ3RPU2NCYXIvTTNtVncK6EVEvAdTzJptn4OHrXuwwseN08hr7cof
            pGUglPgX2sZOnwuGSnyirawnEJBq+z56sQpphejVx1WU0vEET1s+sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-22T02:41:09Z"
    mac: ENC[AES256_GCM,data:lZ5ghsUrItBv+vhREKc7SrkEpyUWBPVlG2dR5y0z8x/bDaD0zjOtSAV/N6nQ33lAEMMU4VD0gjCAlvM7QFE7HtjaxD8wKqJGEv88rrqQHMI+NYpRI3ySCh8QR594E9QGrvdDvzR7yCJMtOtHKU7aVviQuBfGRLxJKQqELAlLbfc=,iv:bIQU9MUPCs4qgrdHCE/fAoR/y52Xvde7vGAkPbe7EHI=,tag:hSzg5yECvMqcrneM2iwIvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
