apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL2lKYUR2Vjh5U0RKWCto
            blJleDBrcWVJOCsyWnQxNlVRNmIycEZWRXpBCmd2RlRCbWt2U29ZRTc0SWlkRUVU
            NTBnUzhObnhPdlFKcnlZZmVjVEx1UHcKLS0tIC9ob3Ryd21kSXg1UkZ3VWxwUk41
            M0RDdk9EVmVNMXVaZG0wYytJQVNmdEkKXBAFQzvQvd9Eoi6oA+X6F3GhP54IbFuu
            WW8ufPwe//NoZ4cv4eQqenTBj0nuW5Lv/mo9itVToPBjBvZuUrLK+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T23:23:22Z"
    mac: ENC[AES256_GCM,data:1TRWIHMExs+zRpz8nlzIlDiurA5O7uY5qibelkU+OaYzJoYzMY7x61oirdPVjcalhOw4cj11uqDCWTya9nY2bgHvhRCCTPCyDxHuVl5Pjf6JHeqYdxUQNtuQ52JICfx/5kQ6V0d0LdFaGiPMVhjT8+e4FJlPM1sZL0ro/aXl1+Y=,iv:HH1Pr/OF2rcLJphmq+358f1Hc+sMShzxiHByg1eyEJo=,tag:oIRVqEFfLQysl+9lybN2Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
