apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:6MiN/xQvXR3jnOxrrj6M5c7/KHQZdWrV,iv:nDzltMntfKTruUQ+DBFaD890PrIxvysuu9v5fCJyEAo=,tag:yMenEVMRuOTwgkXFwLpzmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQlBtaWZmSzN5dDgxc3Ba
            M09DOFJpQzRPZys3NGI0Wjc3MEVDejIzQkNZCkdMVTBhUlZvSEd2WDRNYlhDcW9q
            bVptb2tpV1FROVJtK2Q5QjhwQWdYa28KLS0tIERQYlpSTXJjOThxSFIwa1ZWOU1s
            NThqVXg4TWJ0dnU2dklhZ28vc29GUWMK/Pg0msM6rH/Y45VfsKOJ868TwhroX8nx
            o1xdGrVokZ1YYXaIYCHvvUhePnyeibEFRcycLtG2VaWBDMh4OLLwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T01:11:21Z"
    mac: ENC[AES256_GCM,data:A8ebhFvs2wRtnOJGEcIFwn2zWeo+vGOj8QO3fLoEj+fOqjuIQNk+KzNKTj66ZseDEFA1NMYYwAClr/f9ZseYnl9cvidhDt5Y1NFAZRJ3oMRHatgEKsFgbFcS51YFH7E8A43/W/HtoPnpFl9DdjuXzxSiDq2xA3LPIU9yE56KPWQ=,iv:EylU4wo6HtlI2b9KKm1Lxww9oyIKaPfYknuli6LfFUE=,tag:HaF873nU622yxs1ia+ML6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
