apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kcwd5BGZRTc5kArz9lku8tLRkEfJDp6tNJaHGIGsx3qMOe3mBOBihQ==,iv:QrPT5kBJ2UhDmNA4pl29WMJlRLkungiyFZ7Cmssed+E=,tag:rQWMAlf3lxX94jC1da4o7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bGxkNU1BdFJQZnpNLzZE
            bjRpK3NNdDBBQlVrL0g1TUp6MDdKTy9OdEVVCmhSRW1vN1dpbVRFa1o5RjZIb1M5
            WVcwMllEUFB6YWFGK2xLTk5DR1JJY2cKLS0tIEdoUkpyWkFXeldDYlZPcHZ4VVl4
            amR5a2FvaFZRdndiYjc5NjVGSUZCcG8K68KxJoAcGbQ9FLptQmunCltS5QALk5Ck
            Wmv2yVnSNz3fgAaFql2cUDAxRngm8KYvUqKz3scLlF85QGBbr5IP+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:26:15Z"
    mac: ENC[AES256_GCM,data:DIb8gqWvEXmPS8NXV1rhv1E5tSjtxbSmABd/EdlONfabKqRjPPNb4kErgmSC2RldZE9ke3z6qhHcDaZhRO6PYC9U/Ji03s0YbXtCQGWp3e8lDhLkW/Xok8cqGFOBoR34+NzxuJcrXxu49LSOGVWdFrmE7ILoOc+MmyftEr7FROU=,iv:3DgPbCYNJFSSGLox22jDITb5vQDn2aCIBUz/sRy77aY=,tag:1jr1MK0e7z11sp6PPhC5iA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
