apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:ZUiM3Y/7GLVpYZ5HvJLoAk6EZK7cl5yxAE3TX48wQNPJFz5BDkS6/w==,iv:vYcjnLW866b6pzRw7pLICPLZGVSFoJV3d1xSrUU2Bes=,tag:JpaGzvOj6qafoag27e7FxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NTBYMlltNGhjQ0lWc0dT
            ZWZoUjR5cUxBeTJYN2FUai9Nc1BtV05JTmlrCkF3N0QvRXZUQ1BrVUg1VXVySUk0
            QXBrYTQ5cVc4TER6TnEwSkFabzVnMEUKLS0tIHZYQXUwTW55TFdYT0VlS2ZnUUs1
            WGUyWXVNSTA3emtUWGxpd1VUVjVXVE0KrFKyuwltC7+609fuMS3jvBnQ10tyexlo
            H6Q6EFAytrOnTGDCJQhIkSZ3NR/1EhK0E6h49ge25epxLRid/uN58g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T19:45:38Z"
    mac: ENC[AES256_GCM,data:HWyY9qCN25rubnWxqxIM6irpFSEzk6khdRnGaTjkKYjeQ97TyHtK1T0OZSfBd9u3HAFMlBuWqh3GWX4NnmCKR+qgawWoiMpIQmmsgAfB1A1ejSNYSlkD4gAIBrqAuRg3VXCunSxMaNsv217lAIc9z4l7noKPRmApiR3i8hubWI4=,iv:NNWsqgvUSEPEgg906Z+aJCxy6CYmHeUtZRvO2i8J7Xw=,tag:9/bYVl//VOdKSl+tEk/hlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
