apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:haGO8qcWubVc20uLFN7MkpEZ4kcilzj60MTn3utuACHNl89pvbf/+Q==,iv:1T6uFE0LTZp0THWCeJNtq9D1uS5EisosU+C7hzAHjEo=,tag:nSbGgSx0E7jYyytXNigVTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS2ZmMk91cm1ZS2UzYjBY
            NlloZWJFOFBpOGdZVnhmekZQT2w4ZnhLaW5VClpuT1dsc1JFYTFHNmhXSSszeDlt
            NUIzZkhjektDYlpMay91MndncTYyMU0KLS0tIHcreTNMaG0rZkhBZW91MnJoVUhR
            L1ppWjIrblBrMGtTa01XMkZhcklmbE0KPjCvdF88IIfIP9oRE9CTAY0gS/srHzSk
            IHKEF3pqs7ij5Lz1NYSyuednSpCkwANXbor0vw+XvGIIIK7wbLGUTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T23:59:50Z"
    mac: ENC[AES256_GCM,data:vbj1/gif9+0oQ24hnDkXIhG4NovlOvBM8vjZrHB8dfmHOAuY3j5nam/Wthx5yruYNNeUKCPpa4YzZHy3Mv6koElPm289BtcQryUqhB2pnANpKUMQ8qmQoydhyqkutxSXmfwkJeDz76iexBz+n0y1IdOzlzDO8OUt9lpb2UMkr10=,iv:dVAXusnqKMJiA6IKRaSJIDdPtS5HcYqdhGBRnTiX/mM=,tag:q/QSwJzoAhUE+UUN/6I4Xw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
