apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:BK0wtBoQEMFgb3KfJ2R2+x/kDnrOCA23C25CKeB4hZEdS2+1tSVk4A==,iv:wRg52qDGAQHZJXwoQMi+P/f5Ci5SSKluJpuEp+yJbAY=,tag:q/hrfgQNhq3J+wN6lEIQMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcEQwL2o3UU9zclExbDZ3
            OTJ6TVFQQlNtNzVFeGRDeld5Y2dlc1E1N1Y0CnZJYzVuRzh1NGFCUmh6cW1TQ2ow
            ZGZ0RnllRkdFSno3MVRDRTNyUE9CVDAKLS0tIEFlcVpBMDVtcWVWa2pxejNwNldJ
            S2FBQnVRNnl3RW4xeWVlNDNoUWtNUGMKeQk4B7A1BXVJJKFdvhmLuTNKxDefOd3C
            wKJl4j1PRf0sh4Kxh8Y8XTSPeUbBeVAv6rKc6UKlNPxBjesZPfDzBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T12:27:11Z"
    mac: ENC[AES256_GCM,data:YKIKCng1V8yXiPXM3J6nfCHT0ThxuiaGUj+uiHAdjI+gG7td2swlGzHwofN0eVwolGbKINR4YMR06Yjq2HPnY6+O8aQPMDX5PZ61OQ80SoNl/vnebba1INEzNFuSKKKPg/IyLJR3Krt+oD+Styn4jVPYDVik0rmb7WHMdWjqK/E=,iv:ROpsHwxhKE3l3iIol/KQjVZzzw8RtuvCw/xvE85p4Ew=,tag:oG+c9S5w5j6vmX3pAyYnlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
