apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:u5PL5pVBX4Lww2hqHtf957gyXEVlGLOZZb24RCIC674UjCTijuvn9w==,iv:LrvgU8eUGr/sfqoD8sAErVJa8gIn/yiEtXG9IusVqew=,tag:VLmfmMlfK/G5s4eDdUWJPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRVZZeE1pMGw2dXdFc1ho
            S3Q4Qm8rcE1jMzcveThwclNHWnBhQ2RXRFZvCmp1dGhsLzVtZmp3SEVEK1c1QUE5
            eHh1REQ4ellrYy93OTZER01XODExUzgKLS0tIExyKzU4aVpZUm5UMFpJSE0yMm9r
            SzhvZXllN2grT0dIeW8yN3R1TEsvbjQKxZLXDmnRfqdfI0ropNwiNa+kFiPC/sZY
            tBonBOpZpgPnVLV1TKh6uj6NcnwJgIg8xJ3euF4vROSyiayIR+a1Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-02T23:23:22Z"
    mac: ENC[AES256_GCM,data:Nl713ZP7umWvOZ1hzNF+H+JJxkY2bu7oKNmOarzSEhQo/u8/T0VH5XVFbzkVCmAKcb22jHOEW6b4JXy9bAT1VnMVVi4NTymcpOwS2qlPAzw+EcOdLTP+SwKWsfhp5Wnqv8BugkkbhAOLmG+wzQ6bDe7gOJi6TGFXYWvd1uf7rAU=,iv:g0rUh6VeEBFoqip7elbLr8wbiTx5WtnqytXap7bERDg=,tag:zpAN2ydzyI+FIxqR2J+6OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
