apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:JhjKNVozzZZmU/l7xN860b66fE5QwSrdUEhO3EGbVPD9tkMS+0XE+Q==,iv:f6fhiq1rcuQIMpba1iigQBjsr/IJN09esMZSWodW34M=,tag:pum/K+F0bAO2lxWJkT4O7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQUhDS0pmL0F6NmNoZ3E1
            YzFCeG12Uk9HMnRNSmxBTW4wR2wrQVhRejBJCllESzRuWWM5Z2dwUzVYQjd0d3Za
            SFZlR1NQakN4NEhObUphYkVOWHV0L2cKLS0tIFNndGtXbUtSLzh4WWYwcDNER2tM
            OXZiQWVESWdHYlRucTd3ZDR3Ymw2MFkKjPDXl0sSJySxlwd0nVgPFnAn+tQs0RxA
            SWzpSmV5FHwuUIvBvC5GmKuD+LAtLZTRBtXnC+4EaPH6NEIDX7HZHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:26:15Z"
    mac: ENC[AES256_GCM,data:Mi8m1eznm1Ct0fyTodaedKCxvgYjqxa1xtwK4qqIl6jLQYqSeLPr8qL0FwOrF22BMT2kgLb5ROpGB+Kl5DRn4cyv1NwHvBmKgUtm1Die/GktNDj/jK41qE7Y96eUXHXOVVb7utjVIlyufOgTdhFuMefsc8cOmbO1yJd1N2JqG+o=,iv:GYGcQEEsyt/V3XSTf9o6Ojw8aN116bX5xliZ1uVjWPY=,tag:fUxLuVgsF0bTVaOxyS3fqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
