apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:rNUfGkOQ4LAvXy95vklMxVp1GPBK0j80Ik7UqEUOQd7w9qVF7h4ekA==,iv:2/zPIxyCkLz7mPYIJDcqoYX0rVlnBF0dZrHLTilrbo8=,tag:71f4oBhbaUxKhhEYMk3hQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV091YUExZGk1M3lYSDc4
            RmZFbFlQZ1NGZS9xdGNnNUNwRHVTb1VEMFVrCmR5SFl5Y2xrT2pyNFd3bytDYS9k
            YmREY1h2UFJUaU95QldMbEllS0dseXMKLS0tIFZOc1pJUDBZdWpLZVlNSHVQOXli
            dGErelZ1YW1HMXI5T0Z2WE5YMlJzbVEKpA59wBPdIlYajNtjlArK+N521B/K+6VG
            rg5VHDSx7xI81y4MY5p1Xlv7GH0sPno31Fs4QMRIW1ej7GAVBgxseg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:30:08Z"
    mac: ENC[AES256_GCM,data:g/3hEbxPKSscZGl4UecHh0MyeL8DmduFoq7IQUgNA9nlM/9YEF5dKQ6KTyhun9b0mIcldQqUH34CukVXWtRmqhSczfY23wFvAL7uh1FzrF5GndiQ8LMFlAD+oHsI9hxB3g9qN1ohGo4LcVZUFpxIw+5s/ZGjduPDK5LAHt7MejI=,iv:0LZUMDb4xRNEB80JVgu2YIs1bVngOhjIhMW3ep4NlKA=,tag:T1jTAU97N3tWwZmK23UHKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
