apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:OIVm30oPCycguskaPw8wYg1oTc6aYWABrwU/NNakrRdU3Wc6A5V7Rw==,iv:mPdrAQdEbdlQcmez7uJ+NO1SfQuaVTZIURUhYibugeE=,tag:JVf5Y7rAu0MOHoe2H7oUAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYWJGZ1dkVGxOSTd2MjZV
            ZERKQ044ZWVjVDdNamNkTWIxMGtOT0tqNzJFCkdQdUJIdnlrNFFZdjdIbzNrUld3
            OGFydk43UnlscGJlRlhSbmFJczlieDAKLS0tIDJOT3YvaE54ekp4MEtvNlJMMzcw
            Z3VwUy9YWGJHZmphNzdObUt2dU9iY28KlJzdHRlTVLAwhHxi/BmTrxXutQZXPABK
            y+fSlSWkJVDptDpnZTU9jwVkdaxOk8b7V5IiFhjWONeZvwQErxCr1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T02:32:54Z"
    mac: ENC[AES256_GCM,data:i/t7MWZ2y2RpFMCZbiIxbnz9m6SOeNw1jH+b5ekd9hmFV60tnNxQV7TeeMx+3S9tOA4ym8FzicBZDGEl6//5vDnDh8iU3o2nZT/35yoWM/epC2zSNDGwAF30+IZaQUS3UXnxk9jS/uejG+OG7tZXTODdAR5sEVphFagU3OS97e0=,iv:u9ezJDUh4Uc9zfhKRobxbNwxqrMGk7+PfcmkNgS4nnY=,tag:wanppzEq/pURHBnPPtYMbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
