apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:K9QmWQIQzluEiFcMv8K/Vm/t,iv:XakOkyuFYuo/090GNBtfmuJ4WHNMggVb6m+rUTa2TTM=,tag:OdL011VahqmdcSN+v33jZQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:3VwJJ4HW05SW630/EY0fvBJPmFMckthkJr6+iYkxzyQ9CGMv,iv:yXkDDAA+jNIHJJekcHS6asWAJpwaD3Mt2s4KO0+ELQg=,tag:g49OaExfiGLD3Xi2xlicZw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:cryl9fgeghsBgO4=,iv:kDsKu9Oks/Tn1DUd6HMjIpeS22T3ku4MeHsnTTcu1TM=,tag:GEu73vzoT4QZroVnfAFv/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VGJEWmZodGNxS04rUlN4
            a3pwbTdDUVV2VmVvaEI4UVZYVmg3dE5LamlRCkUzaFJtZW5nUmFqMVp0V2Z6dEt0
            QTdjOGl4MVRvaUc2NXZwR0Jrcy9ldFUKLS0tIElpVk9tZlZtRjlXeFNmMmVTOGRV
            ZyttVjJncE52S0RZWnJTcGJWMGxTSlkKznTYSgakrtjqMGecxGgDfYV11dZkYfty
            dNkuJEkua1ara74NLqvCrH2eTcvHOvcsuQQ2dkDOYv5mROwZNY9CPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T01:11:22Z"
    mac: ENC[AES256_GCM,data:WrKKeYgDlSdXoVaj00BGVOre6PsxKd0otT9mp5TjjjVk2TYCXEIMvatgTEdLi/hQfgdGnhxD1I5OVDWlIAcFOo4SzO6bX8RGVYC/YFEyViM12BfI/HX3X2Rf3Lp+9jkfqn1fY1N7D2Dsn5DBULILjS5Weq/XzZcoK3bN5hTtR9c=,iv:2sepkOvyR2DaEqb/+CjuPmQIImLZRg38qstqj9kkiBQ=,tag:RG0cdu3/CBbVZNTZYmXHZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
