apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:FGhPuXGQXfV0IZshlEqHxHzv,iv:l9Byw2/YKt/mRi84SFlbdm9x3cai6rVFB8dFM5ysG30=,tag:mtsOkP4DP/4c+e6bkGVvkA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:W6be5kIrvhuhlTI2gP5rSNjL707ZQPANsmrHGopCYhWMkp8h,iv:bz+7nq2OMGAZ1wj+EODYK0Z8Wb2Mb5ivJ6fVlOI4yZ0=,tag:SHrt0vdPkBGk0aa31N5e8g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:DXbpCnSdMtsaAo8=,iv:D2MBvy+lb9P1NrnE0JfX/l09vYgP06Bf+BqvXN0WXmA=,tag:xJbZoxSJ5hRIT00YJop/6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSkgxN0wrZWg3V1h4K3RJ
            V2VVM3I2dDBsSTlnMHFXbTlkWlFNam4zaVM0CkkrRzF2OEhUZTZiTGhveTJuRHJp
            UlcydDhrbWoxZUs3dUtpK0tRdHlDb3MKLS0tIHErT24vUnNpb0M3b3cxTFRBTi9G
            Y3pCU09sZEhTZFhjQzliemxwbGxTQ28K/TtDB9+9ItR6kA1Q7kIPjowFBfhStIG3
            McS3T6htNH6nbgNQ2sF0UfQpBuY+pp61Xp0QyfYG4Tz+v1odMxT1Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T19:45:39Z"
    mac: ENC[AES256_GCM,data:HNdRIDJrIdGdrYOkAybmwo+yKCYE44OobScEcHwgqb44ycdH5gM0AOaqs6CB8v0jn34kvvLKVBrISA/jtr/ZbKkqM5r9Dg3uWJMbwyxbxD+eDRF5CmNzuYGJHZIQGwz7Qwze6KNdhkkkHdjrVnt4235ErOrN0+WF67H52zWEJ8Q=,iv:hz0ephuPQvBzRuJypC+n5/LSFI5HOgA0+ZTzZLqajlU=,tag:euXKycfUKYUoZwukJypv8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
