apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:I6nGC9LdR4exijeNPpOwVLxO,iv:GsQ8K98Bg7JSLPvVwNJ4/3Jo1WMB2o7pQJLVmI7XwUU=,tag:B17KNBWobIyiC/5+0LA2hA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:z7rhw3u1COofXZvdg/k5hc/wrPVvp2BJWhbZt42BMzGGOK3T,iv:ywQKK1RKw9zDsUpMApknxA0JD5M5OxRhpTcY+G0VpBU=,tag:FGc97WtUiA25Z9RAbAtCBA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:yafIaq2d5GxLd7Y=,iv:bUtikzS9AWi4K9akXLatMnmg/6Wd+nB2nHBvRFlmxb8=,tag:h0giAKrny7YgnwqmNgKDlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRHJRZVVFMlo3MkYwKzlY
            cCtSUURwaXpMWERNakNQNlBlVjFCbHVNRnhRClc1U0tET1JQdlhZcTRpbS9GeFJR
            N204VFl3ak5TQStmMUdpb051VE1ycjAKLS0tIGdkMXBLQUw3TldGWWpGQW1TMWpz
            Mk1KLzVxNTNQZE1Ha0d0Z0RqOEFxOGsK8nVv0JtPRScyH83aqHWpsGXiPigUupk4
            SPnBxRxi8t8RAZ8/bLznctb9ikQzPiAxX7+2vRfhgegwA1u8QUBZdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-05T22:17:09Z"
    mac: ENC[AES256_GCM,data:42ggoGqOHvZ+sYTTZ94NG7elUQnhjVwsqMRXkpgGo8wcBdpayvScIbEgJ8d2LW/qTZST5mswQjyTNVp/VFB5K3uRX6+EOFZiu5ySinEXpBOAMnf+zhp4YVamqsKnzAVzYEorSqTu2SSkFq5Drt56C4T17E7vJk651hvXSDpTehY=,iv:sVjEHItAjyo3CdNmXmIo7zwikRe6KP05ZpEp62X5iVo=,tag:/NqaTHFfJ5ue00jgXKsp+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
