apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vv1ZB5Swc5qyamIdEW7Bxw1P,iv:c471j/zRbqBQpcfcPXcbTlUf39bck2TSYcWK19W1o2g=,tag:ATlibespfW5fSSrDf1MYZw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TKcYeaNKC0L7VB+gKoWfgMQiFFb/pCOQqnbYzASdc3Ii+mQN,iv:frnUg1IUYqtcbZWFDOAriouw1SKoxcIYz04kpxetcio=,tag:bQgfMtAktksOKp8+vcd+5g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:uwwij67UP8ZkB5Y=,iv:IriX6LRSdMIjt6bjxvVtOKprxL9db9RyKtyspaYLd9g=,tag:WmuUt1Kg28W+Gc3erNBP+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbTRLY3BKcWxkTFZ4Q3dO
            aUt0ekp6L3l2QUI5WHVsTjBJWm8vWVNsTDJZClp3aVhSQWd4TW5XMEZJZW9HOUxH
            NnJhVi9QbU8zajNJZytLeXlTYWdXSFUKLS0tIGFXei9OODZQR0JiMGhrTjdsTko1
            dTlPS0sxVXlBT044dU14NHlSQVJNWk0KX4t9SewNrfhgem+2t542rlwgM503dX8f
            ZU0wPoJJOHEdGd4pqFpABVLteg5dmiOMuPNinm7u6VFktGs4CtS0jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T12:27:12Z"
    mac: ENC[AES256_GCM,data:qZpuzgdQuZAkqLzrMUQfHL4Fr0jXpk8DtUfTM0jRrs8EH8c0lzIP2f0q85Qui/6vLYZBZI6/cij/bHVra+5S2CM7pVg+0euwAASNZ8ZOBo343nnh06kBP9Q9Elseur2vOcpnoFNEshcX4Y9boQMNC1dwbZMXdpGErlpKFuhTuPA=,iv:YGkoenav4DtMzLY5fspeSCjEFgji8lorH3uXhZG0YEY=,tag:5AETO8jv5ryY52aeWjYMnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
