apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:XB8bEGfgQa/ow7JC,iv:DhVJxPfC3WKG9JxeX3DQH10wHsAXINt+jxCSh0/yYEQ=,tag:5gdtXw+sR4O9szAfxPm8Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMHBta0FZc2ZQWHphZnp5
            SGNZc1Fobmd5MGJqdFVBSzFMWlhya01BZVRjCjJ3ZjI1VW1oNk1QeTNPWnpScG8y
            TGtPY29qYVJFSjRVTDlyeVZSWFhUK0EKLS0tIG5jMXFrYTlTQlFkTjI3QVVSeVZ4
            SEQrejhGU2l2MmxYNnBGRUU5elVnb1kKVQUTmeQah8aXF2PCe9+kYuSK0rE7Cn9w
            dinaeipq4iOVyA7Syo1tFzGGY5lqYvFdmfhMyqVaugjTxv2ZyFLGkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T22:08:21Z"
    mac: ENC[AES256_GCM,data:FdhY701382yM4qWVUeRLJpIfYOI/HrTbV4lhVuM/YGVMhoizGSP7/c5ECv4sGPBwLXZHSROSFfKPbTOpIIIQYPXC7ZUuN23qL6l1kXRAFrbnuqHaD3d7O9PHeVqF+Xgi7QwIDblsz9tKke7hfEJ7mG8ehccgzwFYddwGmGEv0pQ=,iv:tUs2ecDbEyMC4ChmL5rTqGFm5Xvadf9ezdFulbHCguI=,tag:mSwH0AdaVpxZybhP+zqlKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
