apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:WBEeLo/bNNR1IfPG,iv:kVA/q42HAXj7Of5CcXNjoXO9C3RGIxYEyE/lKKhcZEo=,tag:Y0Y9qibZlrxYy+0n0Q5UCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bmZkaHVkY3lyWmRMT2lh
            RU5paDNraFdJYTFubzVaTC9PelVGSGNzWVJJCmdUbTR5MWFtU1FOUmhLeW5CVVF5
            MXRmN1lWeWJrYSsxWUpQV2txdlJ4TncKLS0tIGZkK00yZHlCQVYxM1pLK2VhK1V2
            TU5uNW1vY0VEZmUya2w0WnM4RGwyMDAKSMaJS0sofLLNkww07Qy75fN7FSRlajpg
            rewKCqIrtdjk5GaYgxMYRnOeUWSD8zUOer7OctA3uVQ5aYfnxOiX/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T22:40:14Z"
    mac: ENC[AES256_GCM,data:o7/VWJehfTUQ9QASb/KAu1TXZ4Sk7xWio1+GUVNcb4Ryudz8YBUtawB5jD2sxnUY+ABxv35tDHQPdVYPcjYY6151fFNr7WfDWcNtwvfAO1H8wAE46XkL/hKaMqlFMkuDGLqX1vUi/wi4y27Xb1CChN37WtoNrhKixxlD2U59A08=,iv:NwQklcDLvOhHERgpg4bUzB5qpcBjLG6A5b6EydtVkqA=,tag:XqPiiOSTQ2T2uXkAky98mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
