apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:pslxgKulPO9C5Nw3,iv:gk08q+O8X4yradUaRv1DchklvMPxudM0k7SU+MT42JY=,tag:MezXO8hSgnMUGHYO9YfDxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdzFhRjcxQjhEWEZ2SzZs
            Z1pIZ2p5cDJFK3M0SmpQbUgrUUt6aGZTMVFjClNQUEZJZm5FaE9kK2RjM2xyUG14
            TnRsZHkzT3hIU2EwWmNGZU1vdHg4Wm8KLS0tIENkTUdLNUMxdXQ3cTVTZlFkYXNL
            TnJwMk9BL1E1V0h6dnJqTVlDWGVDbk0KQ6LX8aIyIRRH4/EHDxmlpQrwjj9qe1BM
            OBsXD4NYdWKKgXvBrg5MDJjWjbHL6tYAjfZ+S3+oR1+oexmCcKNXSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:30:09Z"
    mac: ENC[AES256_GCM,data:LZ+foJ6f7N6ZgXPCChP1Xlu32jJ1mxFBmOzt2AGvIk+PozM6NcGBcBKRb+t9tLQ1lvgS2dwHyyQ7m3IoXUX3ArsAecvT35esgJ51NMnoZSzkPlYyrlKnO9llNEELkt7o9lyh2RrbWPSmXSTD9GJhOuP/ByA0Spt/yFqVG90Z4/w=,iv:ZKZiAzgeYb7cwqSy3+Gk3u+V+HLR0niIT/8xp81Kf6w=,tag:DZotuIICB7fAnxE6VpNJjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
