apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:29B76LJuOrPRAF7FZkwOJXLY,iv:y38pawXc36KTXEyLEu0lmJSCqEMl3ZsRdDoxVfQaT5s=,tag:wPp+2fTel4UvjwJcnR63vg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:IMvu2md0dr6rEe7PP4DO1lyjyXtoJNamvJgVuifBBWOaol/B,iv:ngG4U3LysIcDfzRleZgWJkojx+UeaFT9Yt+InObMw7s=,tag:Z6qtBlTmMwmoLELdgR8Www==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:rB5L27gO4u4NHvs=,iv:p3kKI5V8ukIZ6DXPh09S9MAw9XarzriqfBu0CC9CmB4=,tag:Fj2y8qMn57ECXrmrbSnFNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWWtaZXljcnI0Z3NDc3N3
            RSs1VDZPdGN1RUlxU3NYUkR6Vmpka3U3bjJzCkNTNUpXMmVCdHNsUmZ4SHZYeXVm
            ZEthY1N1aVRJekNmNnF1ZDM3NkdZbzQKLS0tIHlvV2tab1o0TnkzdGdZZTBZSlJy
            QXRBYVBwcmw4Ly8vL2pnaGhYNGRqTWMKs8ilJtFkLeVjWtkoDOOKfxpnCPE6JF/e
            yjGkQzXZ6O7PwRmop1p06EAiqWq/1iwdFDAM+yQnXyArum5zYeGuNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T23:59:51Z"
    mac: ENC[AES256_GCM,data:Kdg4nPswt3HtkPEW9YNTHL5mXUVkzrUwn+oFhsSlBPLpOQePVa0v7dSKYYKM/TMpjz5fpmWLmDxcAbOsiL1dE6MenhAPNS+fa6K2MQC/b0z1M1dZ8MBPZiklDPOGlw5T1hDlZhaGR+bEmaJimfmF5o7Ouw5COwDiXWEhs6tjcuo=,iv:MitNm5GO6pISZTiqqxRume0UfM6/FRcgs4D3bwy9Llk=,tag:lO3sSvbeHFbW77MYLSOe3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
