apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:VVGhfI9rgzyr+4Fc,iv:5VREjFAUD2BusLs+rm+0AU4KZciZWqmqJiU1un9nxvc=,tag:fvS0CZ8G7g+OpfBW0DhXvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDK09vb242d1ZYYUtaRE1Q
            VzI5SkY4a2RaZnpVbEZyL1NYdVNmTm0yR1VZCnY1bWxzeHFKOG1CaXJsTzV5d0ox
            OFBZaXFyRHlhbkJ3eXdDekZFbHlHNlUKLS0tIFpDS0dJU3Fsb3pia1k2SDVRRFhS
            MStTb3ZtWStUSUdmWDdxekNiMUtUVFkK+flYkU7w3blC4PjSjxobsuW6CCVEWqDQ
            Pz+0gKWVippz+Nhb4nZV2HGSr7VKr+JZyIeOxaOvmgI5TIIQIiJbrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T21:54:52Z"
    mac: ENC[AES256_GCM,data:RRgDSYNHg8u5Qm1aHXPOzY19POvRlGywaXT0ZxXyPZazmx+y6s17q39uxP8Rjdz0r1cMPCXOL0rSPx6iFKdh5gxGy1d4F23OYh/i8EE0kCLSlQIefG+05uF0kXqySl8GiUWkTCby9k11BQdaJu33RnDyjva8F8STYTtQ4aaDtAU=,iv:RZch37i6TpNEc/YrP7oQpOK83uRdOG8MeOzlvQIU9uE=,tag:lEodOp3FYurrBnK2rXMjgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
