apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Kk2XHawDiAkgz0064tvgPvAH,iv:G856IkqFSl5Hunm6/qM47upY0Xx85nSUev52Izpes8w=,tag:AZPg8w49n0W2R2G5coRoKg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:H4tZ0HxFf0fFejK85pKRj3sgHnP/3uYmyjd7NwjykffwRBG+,iv:ZSWDVdGVq7ZO2kb0FFfdoIbtb8w0eF8G+03ziSG+74U=,tag:Fo5pd1tVjBgK4kzCYbsQEQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:c959MlW5dIeuREU=,iv:Q0nn0Wp0cSmqmwyu/9ycsFq2u3XZN93PElvt/06qw64=,tag:SmKdzff4lgQJVl23JhdHBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WFNOd1lCZWlGMWcvV3hK
            a09wRGZyRjZ6amhoMjVabVV6STl4SVlUVmlvCjlpNDU5Q1pCdnF4T1pRQlZZQWps
            ait3VjBHWHlPS2N6c3pqTVJFMU8wWEUKLS0tIE5NdUZGanZDK3hyU3lYc3Rtb2Uv
            U2FXY29PTkY2TmpuUFEwdXpmaG9KNmsK+IN+vsV6K9UeCyz6LQ7zawRX1x0p2QrY
            QWppZSHHnTnPMfVMbpjyFCGtxxx1Q1ruqiJ28Pxl2KELCtc07bqxfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-07T23:52:24Z"
    mac: ENC[AES256_GCM,data:DnbwF1SR2PG/3ODgB0wxfYnIzF6dxL3AfB6nscvtnqBuTyLwgfMQJjILRKhb5v5QXHQOxZiv3sZoMSfU0kIRSoOkIL3psJDjhXGxVno75w6fr2V4d+W42vMKCOKBPsOef/Ji4qCfG6H+uSXsxIrYCPXVCP0BBY2/zxIisMvr5KI=,iv:hv303U5AyNPwPuSkosdBVLbCTBrvpKQ/jQCYtYW40kY=,tag:i02+9H5AOfH3tZ7Kz5spOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
