apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:S/0xjdiGoB5fApGz7iyzyxbZ,iv:P+ORqRNaOCpZKahicCfbriTMZG/muTAGnGaoaNlKcV0=,tag:0fockx1tQQ8O42/iJem7mg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bJhwNFKHzAVETW2zHC5Wc3KvkO0IYOnXnOvTHCnZGKUR0HvY,iv:YYHl544L8WCHXuDc3eSjGHzWXLO+6XGX7B0OMV3vEEc=,tag:CoOdlf9SDsXDnTaeUcy91Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Q7lXWuLKlVRJ4S8=,iv:ikmVrQjXfnpqLA9cw9AZMy9Dl3lGRjbu238JMCO4Dv0=,tag:Nd2Nzg3ZHLzRxC4vRkxd8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4emFHcUdlZFJtRVBOWSti
            WWF1azl6Q1NDTlc0QjR0T2tRbHF5TDB5VEVFClIwSFVsZTlBdmx4M0tVSzZoRDJi
            dmJhTndEWHpIOFRGSkgvNGFOVktobGsKLS0tIDJnRThhNGsrTmZreWVXYTlaMTUy
            YVRBYVpJZklkSFNrbTNQRm1Fc3ZKS0kK3cmW8YH2UAZ2HNIoBakqy0Z4s/gdxiv9
            d2DPfnA+8dn3FBLDo3uzK6QEkmzjWcYayP5h56/34zOhER+A6mkarA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:30:09Z"
    mac: ENC[AES256_GCM,data:x08M169DKeAGiz62DHCJxNhhg0/SL3xHxR6I/j5f/b9wi8yhcqzl1CNSAKS+mMVTtpDOlwBUHE+EJrOj5Itf5x3BmNSiPMdv0ttUb0Q9J97eyKdFD/LW2e1G40XFK3f8U35q/AZF7It44g1PFcduP2GXCWj5EgNC/wK8snur35k=,iv:rZ6WoLwR5JAh0DmgdWwFWL6U6uzEvtMEDa0lJOVjahA=,tag:WpBhnz4r7rjkSYT7dUREEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
