---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-website
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: gsks0
  volumeName:  pv-website
  resources:
    requests:
      storage: 1Mi # Size does not matter
