apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zRaXiwpiUycIoW7jF9JlGov9ml8C4SOF91y+oOFvAq6ib8RR,iv:mLtak2TvsDUf4UIA14EDKFl7u0qZO9iruqJFEdzngBw=,tag:RngX7uSXgOsh6HMS5M6uNg==,type:str]
    credentials.json: ENC[AES256_GCM,data:gtNI6pL9Qw7yDXu5tgMdHNFLPnLyEaS/7rlq+S61Gx+O8wFKdnkALTdXw81RhRLA59W9Cm9XcSdncV5wL95435mUnDbgUO4HZgV1m/wTRRu/ujxPEZDUUsrA8xlryVLwmBFSFcAYPyr0YRDMCeLoSDzI+w61ZNf9MMrmkNEE0tK7eThX5rH17nFRLHB4SFpdUvBguPWvwAxeWeCSGXRQhiUmn5DUF1/uuG6+oJrbyg==,iv:wLjblisx99CcYgQ3DhPzP1ZTwdBWEe45AosztvXSO8k=,tag:esmGv1Mjb87q4fcMtyt9Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jrvc7mdtvg8kth3pap40a8zkm8468hsrvjsvhl82ha7qhkd5teuqqtp6az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSW93TWlaTEo4MUVxWUp1
            Tmc4RElqOVUrQkFDemFoSkhucTlEY0V2bHcwCmNIbEc1MUJtRXJ4Qy9rNm91NU5u
            ZEpKRFh3Y3NPYXJBNXRDckhvTUNzaWMKLS0tIGptYkMxK2trUXNEN1Y0cDlrTkU2
            S3BYVE9kNVZYZGhRbHM0TnVrU3lpekEKRsiQYGtt8BzA97V6zwajptqcigbljUfk
            GOQrzEj124bcMBznO4xe0gVyTdDq1ZwUlNz+PLiVsfS5QN9DkOP3OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T02:32:54Z"
    mac: ENC[AES256_GCM,data:43lgC6FpN/hSr/DM+Q+WvWO2CJ1smRFxhmBKXHIfwnmkExhq1/n9WGYmhfklTitN1X2TQPdshhThzaH43A2nOoBr6R7Q8d9YhFkZkmO+lN3Aa6CSvaiKBr4Z0v+0S774BRR8xGRfmFcZFTLIa8f7kKS+PmmNlEZlEi4MY4VwcYA=,iv:fUWGKCJ1/D7VH7DBvLvXmqRWpwUjbc/tfG8O0pGp6io=,tag:X072IOaoDroTXgs66CGfRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
