apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:9UhvpIFR+Yfquhs+pHG2pyz3HIJvXQ4ngJyMYtddLbwllA05,iv:P4Tr05KkvbYV4YkdDhwVo8KDaUPOXNIj72OCkmQts30=,tag:fnV7/JRfAEpIY81OvcxnFA==,type:str]
    credentials.json: ENC[AES256_GCM,data:UQX5j3FbXcFKeIw3pDahr7IWNXm3gE3MNpJyKbDq5C/hQgSayK6jOTeo1ZeNy3CPfeqmPt0ddzaj8/Z3WL1r4s1eZcC6om2YhrgW8a4NKHjIYwU8tdDS4HN5MOFiEF99Vpxxa6SLughTDROGQunLZHoa0XjyXnfwr8P98ohfokNSBLXDDOTkYXRM561aDBcQPWAmgVonD/gr1rxmpySnRVYEQN33cg/7o3N/IVEueg==,iv:2jZVnu2mI14wmLgvrUjroA+orH6qaXjiphFUkodFxj8=,tag:em32NBLcJhVXiTTRuTLuOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSXAzYWY3TUJkaEFoWEho
            aGZFYi93YkllSC8zeTFkUFg1dmFFOGRJV2hvCkNFQmduQmJLUkhuQldYTHVNTWRj
            UzNEY2pvWGZZUEV1azdWRVp0U1Z5RFkKLS0tIGdrUWswWlFGUW1XWVRIWWNOcllY
            KzN4L1ViakRvZk1URlQySkpxRDZkVDgKeYSk9smp3xgXPMRfu7ZDVUMOYtCyaZFi
            GK9HBZ5DN4zLoo6IHBB3ZtrSDs3RVq1qHkUgYbeX+hltFgcMGtaByg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:48:12Z"
    mac: ENC[AES256_GCM,data:X7Li8HM5jgxpVHOwg1j7widJ8qvN+BvN73NyuFuUDmC75t8TgsuM4Nll7gKzz7TMEFP9dKarn/d+PfsAgDxh5PaRy+YW/9HK07CxyyvC2xcH34qRMeOBV32PDZp7tXVLlglK6f9Cit46KNtlkJO73KQFi7Dui1ceLCQwf+IFHGk=,iv:wZsjmVIqwOaAKcBvEUnx2qj1uolmEDcreADuJnLm3Lk=,tag:PjwEU4Jbp5wKiN4S0GpQlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
