apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:bwp4E2lVwyqtzt/b1bkzNVponnO+Fx6WGIUOb1RNwcNCMxci,iv:a9AzEnOA04ILEmDcLRnqnVtzYncZLwhiXmBRgcgYbNc=,tag:qN8x2AwMG/ioJ1xDUZZUlg==,type:str]
    credentials.json: ENC[AES256_GCM,data:6DmURbPcxWsGAUJYZivzvkSkmeOja5Xll5TNai2ZiG7FNgtdVYPAhEHoe/EaBD3b/g14LCXsk4Rrqul9KIVVVFpKBDqTyyO1bxscRpcDMthK2RehtRq1K21ariXRnqvt+zP2AEOyECgpbEp9rAKWJBe1kK8UG7HiUvGnv3qXXtxE4iiXxbRGZdfLoeJjTNOtv6+PopxKqhhCo1WyTLs9l+D6R7nsEECaVCV/SjiunA==,iv:DS5opunhncldveRGfMsNhcwU+GZ7pb9eyEpPYnv1m2c=,tag:0MsV5NLg837nfwdh/FmtvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UGpNVy9MOEl3ZWpoRmoy
            cEhzOThzNjNNMk9KbFU5Y2I2U1BQcmUxbFFvCkkxZmZrbmZTbTZaYWt6QUtSRnA3
            anJ2T2xVWEtOenhqaXFHSktPV0FpUDQKLS0tIGZIci9sQ1lNTVVnbXRZeGIwZ3Bh
            TkRNVzYvWHVmdzVJclkxUVVYUncwNmsKQoPonEDmUKh8WfR9qhTOX0EhkwxjB+nZ
            /l5wgwJKnyRTG4YIzJrehoWH+5zFnrORdqPwysV8aFaCLpAyy5JLeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T01:26:16Z"
    mac: ENC[AES256_GCM,data:nwtj2pIVM7dHuEwNp56+gXWQbihwr3wtuy+0GshvuNLnEk5TNWlzGxe/Dsb2PoJc2yFK82TJ0OH6VH75RSA1N+3ubKPWsUzyjzwv/r/NXTbO+WDC8eDV7Q4/uC7PK2Jw4fpsNmTYOG7R4JnBiikf+p3W/i/0+VupmYT18zCB6MI=,iv:IppEmjUsWJkP7qpiMFYgJEElIsYf+TobQOYfj9hqu9k=,tag:nh96LeNc785l4JnRN9jOBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
