apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ANuSSJba0Lzm5t9yViom/qdNC3737sSlls6ta3zwkuEjK9z6,iv:pmqkTE74tIXRPOkdhRZzTiPNKkLzd14hZiRxE4CCMB8=,tag:3eT/MQhXlA8eX7gePDrE0w==,type:str]
    credentials.json: ENC[AES256_GCM,data:VUVowldIAQuU49cbVWymFboytaNO+nhgCB5fH2NIqdyy681P1o/F3Cf2drPi8nlZRzbsKZy2vKYdHqxpmmJs2vdI7a9EQ3EQtgYLOX5NFZlvvV/YRvGzNaqiSRtUC9KfiHirRSVFWkNpO3Yycfo5ybNhJ9UGWw7tsZ/GC8FOc2x7W2UEizg6wb/RYklu/gaKizLLUeerI1TK8pMOcCUZBewrxKRbdTgdfbYRbV6z9A==,iv:pMDXFEXa0tTBq5SIh2VAExDXL4BF2P3z/8KPlSY5NUs=,tag:eqejjU4nEp8YI4RRMXCDrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRnVGakhqd0RSWFJqWE56
            TjJvUWRNektYSUJ2MHBZSkZCS3k5aGJ1blhFClNHempiSDhrcEx0ZGdRWVV4ckNp
            ZWlaekZGZERXbmtucGlJcWlhZ2NpOEUKLS0tIGhjUzA1SUFGaEpDa1dRM1J3T3Jl
            TVFOTmFQbkZiSG5SYVltalJ4K2QwVXMKEjHn2pSSWudfIMOF82r2XsSXv64zYk/L
            OZZOPWCIUPW2xNMXwzFNS0vIZdOC6pp2mUJV93LI6w9svvNkfjp48Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-03T22:08:20Z"
    mac: ENC[AES256_GCM,data:reqlqu9wZ+syYq/Lp9hKmRInt+v3+VK4t9/B6oqRTyZTXRiCtAVOkbDFQmZr1f6Xr0Y1EpqraRl3qbsm7uQOpP3Wo+rxi7bH0I360n0QvkOLAY/TlI1wJ+QKYryajZoyYmaCJT0PTLOHKLmXhzubgt6UaDdMSbVlIqyTWKgzLaw=,iv:z7rzFMhku2HNHDmvtIOH5+iElD4HS6KPfuvRcJJa87Q=,tag:MutWw3TwlqOV4URUgXw1Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
