apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RVKeIayz6wNVNhyk91R/tCUe+AmhezsiGnc2W6YOUa5z12b0,iv:pGB05sJWcDDB8ZEAUiMa2soJLgEr7+VT47thpmHxFGQ=,tag:s8qpMys2C2kmY3ezDNEe4g==,type:str]
    credentials.json: ENC[AES256_GCM,data:JcQffud0lQ0gHDETcui3OQhgbpncIxtySv0gIEzX5hfzzxHuJkeUNetkXZFS93e9ba7/QAawh3++4MgQCxtlFRRstIhczdonHXrrfhsKQCKlNre8Yv7eDpWtmTXiueHyhsBv8fp9C0x4vL9XN3A2q9u7tUwnt5rxKH7U4IBxdbVpjz5M+PddReiLhFU6y5/0EJ5ydEv/Z5kKbkQ+7J6X6KYebQcAtwNIfLcOoZMPhQ==,iv:8/Miv75FwZcYVBVzOZOkHC6b4l5iDK57g/Zsx4UT/q8=,tag:lEMkTOFz2n/WQ7D7kBfZQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c7m3llf895a3ssjtxul0rt34lv7kwua2t3awhwla9lhpcsveldssjkfsqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcDBwTS9ySGJNbkhSVmN5
            dU1KL0NlRklza1VXMGMxOTlKZm84Qi9Mc3lRCm1RbEpHdElxeFNPdko2eS9vK2xL
            eUxaQk1uNjg5aHNGY0FUV3F4Z1lKTXMKLS0tIFVvb2xreThCY0VtN2ZvbVZzYjQ5
            OUwrUmRaYkliVUxUaEgrVS83SS9raVUK0+hBbSNZCniP1lmvuA4/92c4hnd3rzi2
            bPXQJI+EbWB37LOoiTvhsZJNO5LgKKWcUU52SbNDJCdK1SpBFe0JUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T19:45:38Z"
    mac: ENC[AES256_GCM,data:vLM2Rw/LfPX8AkXnkainDKSEbnJZK+ZDvavR7w7OLDbIuK7A3UBseWBhkYiZE+aNyGoxMohW7RZNSRNa1WsIl9VK3ECBGJIl4bh9b5/B8OkAyXi1WO7mlAljVRf58XPIZLdjv+ulebBBRsN+XuWPRV3Bj06qzCeQahO0cRdC+uY=,iv:kF7YP43VOZubj70Kbpq6fgePBH/dpsrdBL6Xolr3L+8=,tag:YnTjqsEalEknzpXSjwmpZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
